window.SUPABASE_URL = "https://idgseccmogcnldpzfynk.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZ3NlY2Ntb2djbmxkcHpmeW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxNTgxNzMsImV4cCI6MjEwMDczNDE3M30.q8TbBY51or7p4K90VrFyEZ3CrRO2GOTu2bCkSvJUrIE";
